src/Entity/Commentaires.php
<?php

namespace App\Entity;

use App\Repository\CommentairesRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CommentairesRepository::class)]
class Commentaires
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $person_name = null;

    #[ORM\Column(length: 60)]
    private ?string $email = null;

    #[ORM\Column(length: 255)]
    private ?string $notes = null;

    #[ORM\ManyToOne(inversedBy: 'commentaire_id')]
    private ?Products $products = null;

    #[ORM\Column(length: 255)]
    private ?string $comment_description = null;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPersonName(): ?string
    {
        return $this->person_name;
    }

    public function setPersonName(string $person_name): self
    {
        $this->person_name = $person_name;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getNotes(): ?string
    {
        return $this->notes;
    }

    public function setNotes(string $notes): self
    {
        $this->notes = $notes;

        return $this;
    }

    public function getProducts(): ?Products
    {
        return $this->products;
    }

    public function setProducts(?Products $products): self
    {
        $this->products = $products;

        return $this;
    }

    public function getCommentDescription(): ?string
    {
        return $this->comment_description;
    }

    public function setCommentDescription(string $comment_description): self
    {
        $this->comment_description = $comment_description;

        return $this;
    }
}

src/Entity/Products.php
<?php

namespace App\Entity;

use App\Repository\ProductsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProductsRepository::class)]
class Products
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\OneToMany(mappedBy: 'products', targetEntity: Commentaires::class)]
    private Collection $commentaire_id;

    #[ORM\OneToMany(mappedBy: 'products', targetEntity: Images::class)]
    private Collection $images;

    #[ORM\Column(type: Types::BLOB, nullable: true)]
    private $image = null;

    public function __construct()
    {
        $this->commentaire_id = new ArrayCollection();
        $this->images = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @return Collection<int, Commentaires>
     */
    public function getCommentaireId(): Collection
    {
        return $this->commentaire_id;
    }

    public function addCommentaireId(Commentaires $commentaireId): self
    {
        if (!$this->commentaire_id->contains($commentaireId)) {
            $this->commentaire_id->add($commentaireId);
            $commentaireId->setProducts($this);
        }

        return $this;
    }

    public function removeCommentaireId(Commentaires $commentaireId): self
    {
        if ($this->commentaire_id->removeElement($commentaireId)) {
            // set the owning side to null (unless already changed)
            if ($commentaireId->getProducts() === $this) {
                $commentaireId->setProducts(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Images>
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Images $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images->add($image);
            $image->setProducts($this);
        }

        return $this;
    }

    public function removeImage(Images $image): self
    {
        if ($this->images->removeElement($image)) {
            // set the owning side to null (unless already changed)
            if ($image->getProducts() === $this) {
                $image->setProducts(null);
            }
        }

        return $this;
    }

    public function getImage()
    {
        return $this->image;
    }

    public function setImage($image): self
    {
        $this->image = $image;

        return $this;
    }

}

src/Controller/ProductsController.php
<?php
namespace App\Controller;

use App\Entity\Commentaires;
use App\Entity\Products;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Repository\ProductsRepository;
use App\Repository\CommentairesRepository;
use Doctrine\ORM\Mapping\Id;
use Symfony\Component\Form\Extension\Core\DataTransformer\UlidToStringTransformer;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\ORM\EntityManagerInterface;
use Egulias\EmailValidator\Warning\Comment;
use Twig\Node\SetNode;

class ProductsController extends AbstractController
{
/*     #[Route('/products/edit/{id}', name: 'edit_comment')]
    public function edit($id): Response{
        dd($id);
        exit;
    } */

    #[Route('/products/{id}/commentaire/new', name: 'commentaires_new', methods: ['POST'])]
    public function newCommentaire($id,EntityManagerInterface $entityManager, CommentairesRepository $commentRepo, ProductsRepository $productRepo): Response
    {
        if ($_SERVER["REQUEST_METHOD"] == "POST"){
            $comment_email = $_POST['comment_email'];
            $person_nickname = $_POST['person_name'];
            $product_note = $_POST['product_note'];
            $comment_value = $_POST['comment_text'];

            $product = $productRepo->find($id);
    
            $comment = new Commentaires;
    
            $comment->setEmail($comment_email)
            ->setPersonName($person_nickname)
            ->setCommentDescription($comment_value)
            ->setNotes($product_note)
            ->setProducts($product);
    
            $entityManager->persist($comment);
            
            $entityManager->flush();
    
            return $this->redirectToRoute('show_product', ['id'=>$id]);
        }
        return $this->render('products/show.html.twig');
    }

/*     #[Route('/products/{id}/commentNote', name: 'commentNote', methods: ['GET'])]
    public function sortByNote($id,Commentaires $comment, Request $request): Response
    {
        if ($_SERVER["REQUEST_METHOD"] == "GET"){
            $formValue = $_GET['commentNote'];

            $notes = $comment->getNotes($formValue);

            return $this->render('products/show.html.twig', [
                'result' => $notes,
            ]);
        }
        return $this->render('products/show.html.twig');
    } */

    #[Route('/products/{id}', methods: ['GET','POST'], name: 'show_product')]
    public function show(Products $product, Request $request, CommentairesRepository $commentRepo): Response
    {
        $count = $product->getCommentaireId()->count();
        $comments = $product->getCommentaireId();

        return $this->render('products/show.html.twig', [
            'product' => $product,
            'comments' => $comments,
            'count' => $count,
        ]);
    }

    #[Route('/new', name: 'new_products', methods: ['GET','POST'])]
    public function new(EntityManagerInterface $entityManager,ProductsRepository $productRepo, Request $request): Response {
        if ($_SERVER["REQUEST_METHOD"] == "POST") {
            // collect value of input field
            $prod_name = $_POST['product_name'];
            $prod_desc = $_POST['description'];
            $prod_image = $_POST['fileToUpload'];

            $product = new Products;
        
            $product->setName($prod_name)
            ->setDescription($prod_desc)
            ->setImage($prod_image, FileType::class, [
                'label' => false,
                'multiple' => true,
                'mapped' => false,
                'required' => false
            ]);
            
            $entityManager->persist($product);
        
            $entityManager->flush();

            return $this->redirectToRoute('homepage');
        }
        return $this->render('products/new.html.twig');
    }

    #[Route('/delete/{id}', name: 'delete_product', methods: ['GET', 'DELETE'])]
    public function delete($id, Products $product, EntityManagerInterface $entityManager,ProductsRepository $productRepo): Response {
        $entityManager->remove($product);
        $entityManager->flush();
        return $this->redirectToRoute('homepage');
    }
}

templates/products/new.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<div class="container-fluid bg-dark mb-30">
    <div class="row px-xl-5">
        <div class="col-lg-9">
            <nav class="navbar navbar-expand-lg bg-dark navbar-dark py-3 py-lg-0 px-0">
                <div class="collapse navbar-collapse justify-content-between">
                    <div class="navbar-nav mr-auto py-0">
                        <a href="/" class="nav-item nav-link">Home</a>
                        <a 
                            href="/new"
                            class="nav-item nav-link active">Create Product
                        </a>
                    </div>
                </div>
            </nav>
        </div>
    </div>
</div>
{# 
<form action="upload.php" method="post" enctype="multipart/form-data">
  Select image to upload:
  <input type="file" name="fileToUpload" id="fileToUpload">
  <input type="submit" value="Upload Image" name="submit">
</form> #}
<div class="container-fluid pt-5">
    <h2 class="section-title position-relative text-uppercase mx-xl-5 mb-4"><span class="bg-secondary pr-3">NEW PRODUCT</span></h2>
    <div class="row px-xl-5 pb-3 ml-5">
        <form method="post">
            <div class="form-group">
                <label for="exampleFormControlInput1">Photo : </label>
                <input type="file" name="fileToUpload">
            </div>
            <div class="form-group">
                <label for="exampleFormControlInput1">Product name : </label>
                <input type="text" name="product_name">
            </div>
            <div class="form-group">
                <label type="number" name="note">Product description : </label>
                <input type="integer" name="description">
            </div>
            <input type="submit"  value="Create">
        </form>
    </div>
</div>
{% endblock %}

templates/products/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello HomeController!{% endblock %}

{% block body %}
    <div class="container-fluid bg-dark mb-30">
        <div class="row px-xl-5">
            <div class="col-lg-9">
                <nav class="navbar navbar-expand-lg bg-dark navbar-dark py-3 py-lg-0 px-0">
                    <div class="collapse navbar-collapse justify-content-between">
                        <div class="navbar-nav mr-auto py-0">
                            <a href="/" class="nav-item nav-link">Home</a>
                            <a 
                                href="/new"
                                class="nav-item nav-link active">Create Product
                            </a>
                        </div>
                    </div>
                </nav>
            </div>
        </div>
    </div>
    <h2 class="section-title position-relative text-uppercase mx-xl-5 mb-4"><span class="bg-secondary pr-3">Show product page</span></h2>
    <div class="container-fluid pt-5 d-flex">
        <div class="col-lg-3 col-md-4 col-sm-6 pb-1 ml-5">
            <div class="cat-item d-flex align-items-center mb-4">
                <div class="overflow-hidden" style="width: 100px; height: 100px;">
                    <img class="img-fluid" src="https://picsum.photos/200" alt="">
                </div>
                <div class="flex-fill pl-3  overflow-hidden">
                    <h6>{{product.name}}</h6>
                    <small class="text-body">{{product.description}}
                </div>
                <div class="p-3">
                    comments : {{ count }}
                </div>
            </div>
            <h6 class="section-title position-relative text-uppercase "><span class="bg-secondary pr-3">Comments :</span></h6>

            <div>
                {% for comment in comments|reverse %}
                    Name : {{ comment.personName }}<br>
                    Email : {{ comment.email }}<br>
                    Note : {{ comment.notes }} of 10 <br>
                    Commentary : {{ comment.commentDescription }}<br>
                    <a href="{{ path('delete_comment', {id: comment.id}) }}"> Delete</a>
                    <br>
                {% endfor %}
            </div>
        </div>
        <div class="col-9 px-xl-5 pb-3 ml-5">
            <form method="post", action="{{ path('commentaires_new', {'id': product.id}) }}">
                <h6 class="section-title position-relative text-uppercase "><span class="bg-secondary pr-3">Create Comment</span></h6>

                <div class="form-group">
                    <label for="exampleFormControlInput1">Name : </label>
                    <input type="text" name="person_name" required>
                </div>
                <div class="form-group">
                    <label for="exampleFormControlInput1">Email : </label>
                    <input type="text" name="comment_email" required>
                </div>
                <div class="form-group">
                    <label for="exampleFormControlInput1">Note : </label>
                    <input type="number" name="product_note" min="0" max="10" required>
                </div>
                <div class="form-group">
                    <label for="exampleFormControlInput1">Comment : </label>
                    <textarea type="textArea" name="comment_text"></textarea>
                </div>
                <input type="submit" value="Create">
            </form>
        </div>
    </div>

    <div class="ml-5 pt-5">
        <form method="GET">
            <label for="products">Sort by note :</label>
            <select name="commentNote">
                <option value="0">0</option>
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="5">5</option>
                <option value="6">6</option>
                <option value="7">7</option>
                <option value="8">8</option>
                <option value="9">9</option>
                <option value="10">10</option>
            </select>
            <input type="submit" value="Search">
        </form>

        <h1>Comments sorted</h1>

                                                


    </div>

{#             {% for comment in sorted %}
                Name : {{ comment.personName }}<br>
                Email : {{ comment.email }}<br>
                Note : {{ comment.notes }}<br>
                Commentary : {{ comment.commentDescription }}<br>
                <a href="{{ path('delete_comment', {id: comment.id}) }}"> Delete</a>
                <br>
            {% endfor %} #}
    
{% endblock %}